{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.7"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python387jvsc74a57bd0786d7e42806659f952875b0fb36ff24c7d871b66b5c4ec5b4bf2d81c7369546f",
   "display_name": "Python 3.8.7 64-bit"
  },
  "metadata": {
   "interpreter": {
    "hash": "786d7e42806659f952875b0fb36ff24c7d871b66b5c4ec5b4bf2d81c7369546f"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importing the libraries\n",
    "import numpy as np\n",
    "from TFBT import TFBT\n",
    "import sklearn.datasets as dts\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import StratifiedKFold"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#%% importing the dataset\n",
    "X, y = dts.load_wine(return_X_y=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "INFO:tensorflow:Using default config.\n",
      "WARNING:tensorflow:Using temporary folder as model directory: C:\\Users\\Sami\\AppData\\Local\\Temp\\tmpm2qgtd65\n",
      "INFO:tensorflow:Using config: {'_model_dir': 'C:\\\\Users\\\\Sami\\\\AppData\\\\Local\\\\Temp\\\\tmpm2qgtd65', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "WARNING:tensorflow:From C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\training\\training_util.py:235: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...\n",
      "INFO:tensorflow:Saving checkpoints for 0 into C:\\Users\\Sami\\AppData\\Local\\Temp\\tmpm2qgtd65\\model.ckpt.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...\n",
      "INFO:tensorflow:loss = 1.0986123, step = 0\n",
      "WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 0 vs previous value: 0. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.\n",
      "INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 1...\n",
      "INFO:tensorflow:Saving checkpoints for 1 into C:\\Users\\Sami\\AppData\\Local\\Temp\\tmpm2qgtd65\\model.ckpt.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 1...\n",
      "INFO:tensorflow:Loss for final step: 1.0986123.\n",
      "INFO:tensorflow:Using default config.\n",
      "WARNING:tensorflow:Using temporary folder as model directory: C:\\Users\\Sami\\AppData\\Local\\Temp\\tmp_ehu2dq2\n",
      "INFO:tensorflow:Using config: {'_model_dir': 'C:\\\\Users\\\\Sami\\\\AppData\\\\Local\\\\Temp\\\\tmp_ehu2dq2', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...\n",
      "INFO:tensorflow:Saving checkpoints for 0 into C:\\Users\\Sami\\AppData\\Local\\Temp\\tmp_ehu2dq2\\model.ckpt.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...\n",
      "INFO:tensorflow:loss = 1.0986123, step = 0\n",
      "WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 0 vs previous value: 0. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.\n",
      "INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 2...\n",
      "INFO:tensorflow:Saving checkpoints for 2 into C:\\Users\\Sami\\AppData\\Local\\Temp\\tmp_ehu2dq2\\model.ckpt.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 2...\n",
      "INFO:tensorflow:Loss for final step: 1.0386497.\n",
      "INFO:tensorflow:Using default config.\n",
      "WARNING:tensorflow:Using temporary folder as model directory: C:\\Users\\Sami\\AppData\\Local\\Temp\\tmpa612lqxl\n",
      "INFO:tensorflow:Using config: {'_model_dir': 'C:\\\\Users\\\\Sami\\\\AppData\\\\Local\\\\Temp\\\\tmpa612lqxl', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...\n",
      "INFO:tensorflow:Saving checkpoints for 0 into C:\\Users\\Sami\\AppData\\Local\\Temp\\tmpa612lqxl\\model.ckpt.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...\n",
      "INFO:tensorflow:loss = 1.0986123, step = 0\n",
      "WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 0 vs previous value: 0. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.\n",
      "INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 3...\n",
      "INFO:tensorflow:Saving checkpoints for 3 into C:\\Users\\Sami\\AppData\\Local\\Temp\\tmpa612lqxl\\model.ckpt.\n",
      "WARNING:tensorflow:Issue encountered when serializing resources.\n",
      "Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.\n",
      "'_Resource' object has no attribute 'name'\n",
      "INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 3...\n",
      "INFO:tensorflow:Loss for final step: 0.94725156.\n",
      "INFO:tensorflow:Using default config.\n",
      "WARNING:tensorflow:Using temporary folder as model directory: C:\\Users\\Sami\\AppData\\Local\\Temp\\tmp5mtm3ym1\n",
      "INFO:tensorflow:Using config: {'_model_dir': 'C:\\\\Users\\\\Sami\\\\AppData\\\\Local\\\\Temp\\\\tmp5mtm3ym1', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sami\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-73bb08937121>\", line 23, in <module>\n",
      "    pipe_tfbt.fit(x_train, y_train)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\sklearn\\pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"d:\\Academic\\Ph.D\\Programming\\Python Files\\PhD Thesis\\GBM\\TFBT.py\", line 143, in fit\n",
      "    self.est.train(train_input_fn, max_steps=self.step)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\estimator.py\", line 349, in train\n",
      "    loss = self._train_model(input_fn, hooks, saving_listeners)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\estimator.py\", line 1175, in _train_model\n",
      "    return self._train_model_default(input_fn, hooks, saving_listeners)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\estimator.py\", line 1203, in _train_model_default\n",
      "    estimator_spec = self._call_model_fn(features, labels, ModeKeys.TRAIN,\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\estimator.py\", line 1163, in _call_model_fn\n",
      "    model_fn_results = self._model_fn(features=features, **kwargs)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\boosted_trees.py\", line 2081, in _model_fn\n",
      "    return _bt_model_fn(\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\boosted_trees.py\", line 1392, in _bt_model_fn\n",
      "    estimator_spec = head.create_estimator_spec(\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\head.py\", line 232, in create_estimator_spec\n",
      "    self._create_tpu_estimator_spec(features, mode, logits, labels,\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\head.py\", line 971, in _create_tpu_estimator_spec\n",
      "    train_op = train_op_fn(regularized_training_loss)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\boosted_trees.py\", line 1390, in _train_op_fn\n",
      "    return _cond(are_boundaries_ready, _grow_tree_fn, _update_quantile_fn)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\boosted_trees.py\", line 478, in _cond\n",
      "    return cond_v2.cond_v2(var, true_branch, false_branch, name=name)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\cond_v2.py\", line 83, in cond_v2\n",
      "    true_graph = func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 990, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\boosted_trees.py\", line 1350, in _grow_tree_fn\n",
      "    hessians = _compute_full_hessian(gradients, logits, logits_dimension)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\canned\\boosted_trees.py\", line 1490, in _compute_full_hessian\n",
      "    hessian_row = tf.compat.v1.gradients(\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\gradients_impl.py\", line 169, in gradients\n",
      "    return gradients_util._GradientsHelper(\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\gradients_util.py\", line 683, in _GradientsHelper\n",
      "    in_grads = _MaybeCompile(grad_scope, op, func_call,\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\gradients_util.py\", line 340, in _MaybeCompile\n",
      "    return grad_fn()  # Exit early\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\gradients_util.py\", line 684, in <lambda>\n",
      "    lambda: grad_fn(op, *out_grads))\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\math_grad.py\", line 1344, in _MulGrad\n",
      "    math_ops.reduce_sum(gen_math_ops.mul(x, grad), ry), sy)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\gen_math_ops.py\", line 6076, in mul\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 748, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 590, in _create_op_internal\n",
      "    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3528, in _create_op_internal\n",
      "    ret = Operation(\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2015, in __init__\n",
      "    self._c_op = _create_c_op(self._graph, node_def, inputs,\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1826, in _create_c_op\n",
      "    op_desc = pywrap_tf_session.TF_NewOperation(graph._c_graph,\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sami\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sami\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\Sami\\AppData\\Local\\Programs\\Python\\Python38\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "KeyboardInterrupt\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#Training the model\n",
    "K = 2\n",
    "N = 3\n",
    "\n",
    "err = np.zeros((K, N))\n",
    "\n",
    "kfold = StratifiedKFold(n_splits=K, shuffle=True)\n",
    "\n",
    "for k, (train_index, test_index) in enumerate(kfold.split(X, y)):\n",
    "    x_train, x_test = X[train_index], X[test_index]\n",
    "    y_train, y_test = y[train_index], y[test_index]\n",
    "\n",
    "    for i in range(1, N + 1):\n",
    "\n",
    "        tfbt = TFBT(n_batches_per_layer=1,\n",
    "                    label_vocabulary=None,\n",
    "                    n_trees=1,\n",
    "                    max_depth=5,\n",
    "                    learning_rate=0.1,\n",
    "                    step=i,\n",
    "                    model_dir=None)\n",
    "        pipe_tfbt = Pipeline([(\"scaler\", StandardScaler()), (\"clf\", tfbt)])\n",
    "        pipe_tfbt.fit(x_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "n = range(1, N + 1)\n",
    "mean_err = np.mean(err, axis=0)\n",
    "std_err = np.std(err, axis=0)\n",
    "\n",
    "\n",
    "plt.plot(n, mean_err)\n",
    "plt.fill_between(n, mean_err - std_err, mean_err +\n",
    "                 std_err, color=\"tab:green\", alpha=0.5)\n",
    "plt.ylabel(\"Accuracy\")\n",
    "plt.xlabel(\"Boosting Iteration\")\n",
    "plt.title(\"Average generalization accuracy)\n",
    "plt.show()"
   ]
  }
 ]
}